name: Build and Release

on:
  release:
    types: [published]

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'adopt'

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build web panel
        run: ./gradlew FlightDataRecorderServer:buildWebDashboardDist
        env:
          releaseName: ${{ github.event.release.name }}

      - name: Build docker image
        run:
          ./gradlew FlightDataRecorderServer:buildImage
          docker load < FlightDataRecorderServer/build/jib-image.tar
        env:
          releaseName: ${{ github.event.release.name }}

      - name: Publish to Docker hub
        run:
          docker tag flightdatarecorderserver:${{ github.event.release.name }} k1rak1ra/packages/flightdatarecorderserver:${{ github.event.release.name }}
          docker push k1rak1ra/packages/flightdatarecorderserver:${{ github.event.release.name }}